# Generated by Django 5.1.2 on 2025-04-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorasPensiones',
            fields=[
                ('id_administradoras_pensiones', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_administradora', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administradoras_pensiones',
                'ordering': ['nombre_administradora'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Anios',
            fields=[
                ('id_anio', models.AutoField(primary_key=True, serialize=False)),
                ('anio_academico', models.IntegerField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['id_area'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('id_arl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_arl', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'arl',
                'ordering': ['nombre_arl'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bancos',
                'ordering': ['nombre_banco'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CajasCompensacion',
            fields=[
                ('id_caja_compensacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caja', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cajas_compensacion',
                'ordering': ['nombre_caja'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConceptosPago',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conceptos_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id_convenio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_convenio', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'convenios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DepartamentoLaboral',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'departamento_laboral',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamentos',
                'ordering': ['departamento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_descuento', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'descuentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'eps',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('id_escuelas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escuelas',
                'ordering': ['id_escuelas'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_civil',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstratoSocioeconomico',
            fields=[
                ('id_estrato', models.AutoField(primary_key=True, serialize=False)),
                ('estrato', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estrato_socioeconomico',
                'ordering': ['estrato'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id_etnia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'etnia',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Incrementos',
            fields=[
                ('id_incremento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_incremento', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incrementos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jornadas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MediosPago',
            fields=[
                ('id_medio_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'medios_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paises',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pisos',
            fields=[
                ('id_piso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_piso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pisos',
                'ordering': ['id_piso'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RiesgoLaboral',
            fields=[
                ('id_riesgo_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_riesgo', models.CharField(blank=True, max_length=20, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'riesgo_laboral',
                'ordering': ['nivel_riesgo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sedes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sexo',
                'ordering': ['sexo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sisben',
            fields=[
                ('id_sisben', models.AutoField(primary_key=True, serialize=False)),
                ('sisben', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sisben',
                'ordering': ['sisben'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDespido',
            fields=[
                ('id_tipo_despido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_despido', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tipo_despido',
                'ordering': ['nombre_despido'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('id_tipo_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_discapacidad',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tipo_identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_identificacion',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id_tipo_sangre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipo_sangre',
                'ordering': ['id_tipo_sangre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposModulo',
            fields=[
                ('id_tipo_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposProgramas',
            fields=[
                ('id_tipos_programas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_programas',
                'ordering': ['id_tipos_programas'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaResidencial',
            fields=[
                ('id_zona_residencial', models.AutoField(primary_key=True, serialize=False)),
                ('zona_residencial', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zona_residencial',
                'ordering': ['zona_residencial'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contrataciones',
            fields=[
                ('id_contratacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_administradoras_pensiones', models.ForeignKey(blank=True, db_column='id_administradoras_pensiones', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.administradoraspensiones')),
                ('id_arl', models.ForeignKey(blank=True, db_column='id_arl', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.arl')),
                ('id_banco', models.ForeignKey(blank=True, db_column='id_banco', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.bancos')),
                ('id_caja_compensacion', models.ForeignKey(blank=True, db_column='id_caja_compensacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cajascompensacion')),
                ('id_cargo', models.ForeignKey(blank=True, db_column='id_cargo', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cargo')),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.departamentolaboral')),
                ('id_riesgo_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.riesgolaboral')),
            ],
            options={
                'db_table': 'contrataciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostosProgramas',
            fields=[
                ('id_costo', models.AutoField(primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_anio', models.ForeignKey(db_column='id_anio', on_delete=django.db.models.deletion.CASCADE, to='principal.anios')),
            ],
            options={
                'db_table': 'costos_programas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_departamento',
            field=models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='principal.departamentolaboral'),
        ),
        migrations.CreateModel(
            name='DocumentosContrato',
            fields=[
                ('id_documento_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('entrevista', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('prueba_tecnica', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('remision', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('arl', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('eps', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('caja_compensacion', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('fondo_pension', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('bancos', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('resultados_medicos', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('resultados', models.ImageField(blank=True, null=True, upload_to='anexos')),
                ('id_contratacion', models.ForeignKey(db_column='id_contratacion', on_delete=django.db.models.deletion.CASCADE, to='principal.contrataciones')),
            ],
            options={
                'db_table': 'anexo_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Financiaciones',
            fields=[
                ('id_financiacion', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cuotas', models.IntegerField()),
                ('dia_pago_1', models.IntegerField(blank=True, null=True)),
                ('dia_pago_2', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado_financiacion', models.CharField(default='Pendiente', max_length=20)),
                ('id_descuento', models.ForeignKey(blank=True, db_column='id_descuento', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.descuentos')),
                ('id_forma_pago', models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.CASCADE, to='principal.formapago')),
                ('id_incremento', models.ForeignKey(blank=True, db_column='id_incremento', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.incrementos')),
            ],
            options={
                'db_table': 'financiaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('estado_cuota', models.CharField(default='Pendiente', max_length=20)),
                ('id_financiacion', models.ForeignKey(db_column='id_financiacion', on_delete=django.db.models.deletion.CASCADE, to='principal.financiaciones')),
            ],
            options={
                'db_table': 'cuotas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id_cartera', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('saldo_a_favor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_financiacion', models.ForeignKey(db_column='id_financiacion', on_delete=django.db.models.deletion.CASCADE, to='principal.financiaciones')),
            ],
            options={
                'db_table': 'cartera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MatriculasFinancieras',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('id_anio', models.ForeignKey(db_column='id_anio', on_delete=django.db.models.deletion.CASCADE, to='principal.anios')),
                ('id_convenio', models.ForeignKey(blank=True, db_column='id_convenio', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.convenios')),
                ('id_costo', models.ForeignKey(db_column='id_costo', on_delete=django.db.models.deletion.CASCADE, to='principal.costosprogramas')),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.CASCADE, to='principal.jornadas')),
            ],
            options={
                'db_table': 'matriculas_financieras',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='financiaciones',
            name='id_matricula',
            field=models.OneToOneField(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='principal.matriculasfinancieras'),
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='principal.departamentos')),
            ],
            options={
                'db_table': 'municipios',
                'ordering': ['municipio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_pago', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('rc_numero', models.CharField(max_length=10, unique=True)),
                ('id_cartera', models.ForeignKey(blank=True, db_column='id_cartera', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cartera')),
                ('id_concepto', models.ForeignKey(blank=True, db_column='id_concepto', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.conceptospago')),
                ('id_medio_pago', models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.CASCADE, to='principal.mediospago')),
            ],
            options={
                'db_table': 'pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Conciliaciones',
            fields=[
                ('id_conciliacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado_conciliacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_conciliacion', models.DateTimeField(auto_now_add=True)),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, to='principal.pagos')),
            ],
            options={
                'db_table': 'conciliaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosCuotas',
            fields=[
                ('id_pago_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('id_pago', models.IntegerField()),
                ('monto_abonado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cuota', models.ForeignKey(db_column='id_cuota', on_delete=django.db.models.deletion.CASCADE, to='principal.cuotas')),
            ],
            options={
                'db_table': 'pagos_cuotas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramasAcademicos',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
                ('id_periodo', models.IntegerField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('codigo_centro_costo', models.IntegerField(blank=True, null=True)),
                ('id_escuelas', models.ForeignKey(blank=True, db_column='id_escuelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.escuelas')),
                ('id_sede', models.ForeignKey(db_column='id_sede', on_delete=django.db.models.deletion.CASCADE, to='principal.sedes')),
                ('id_tipos_programas', models.ForeignKey(blank=True, db_column='id_tipos_programas', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.tiposprogramas')),
            ],
            options={
                'db_table': 'programas_academicos',
                'ordering': ['id_programa'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id_pensum', models.AutoField(primary_key=True, serialize=False)),
                ('anio_vigencia', models.IntegerField()),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='principal.programasacademicos')),
            ],
            options={
                'db_table': 'pensum',
                'ordering': ['id_pensum'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='matriculasfinancieras',
            name='id_programa',
            field=models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='principal.programasacademicos'),
        ),
        migrations.AddField(
            model_name='costosprogramas',
            name='id_programa',
            field=models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='principal.programasacademicos'),
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_sede', models.ForeignKey(db_column='id_sede', on_delete=django.db.models.deletion.CASCADE, to='principal.sedes')),
                ('id_tipo_modulo', models.ForeignKey(blank=True, db_column='id_tipo_modulo', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.tiposmodulo')),
            ],
            options={
                'db_table': 'modulos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='incrementos',
            name='id_sede',
            field=models.ForeignKey(db_column='id_sede', on_delete=django.db.models.deletion.CASCADE, to='principal.sedes'),
        ),
        migrations.AddField(
            model_name='escuelas',
            name='id_sede',
            field=models.ForeignKey(blank=True, db_column='id_sede', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.sedes'),
        ),
        migrations.AddField(
            model_name='descuentos',
            name='id_sede',
            field=models.ForeignKey(db_column='id_sede', on_delete=django.db.models.deletion.CASCADE, to='principal.sedes'),
        ),
        migrations.AddField(
            model_name='anios',
            name='id_sede',
            field=models.ForeignKey(db_column='id_sede', on_delete=django.db.models.deletion.CASCADE, to='principal.sedes'),
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id_semestre', models.AutoField(primary_key=True, serialize=False)),
                ('numero_semestre', models.IntegerField()),
                ('nombre_semestre', models.CharField(blank=True, max_length=50, null=True)),
                ('id_pensum', models.ForeignKey(db_column='id_pensum', on_delete=django.db.models.deletion.CASCADE, to='principal.pensum')),
            ],
            options={
                'db_table': 'semestres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModulosCompetencias',
            fields=[
                ('id_modulo_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('intensidad_horas', models.IntegerField()),
                ('id_modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.CASCADE, to='principal.modulos')),
                ('id_semestre', models.ForeignKey(db_column='id_semestre', on_delete=django.db.models.deletion.CASCADE, to='principal.semestres')),
            ],
            options={
                'db_table': 'modulos_competencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContratoFin',
            fields=[
                ('id_contrato_fin', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_fin', models.DateField()),
                ('id_contratacion', models.ForeignKey(db_column='id_contratacion', on_delete=django.db.models.deletion.CASCADE, to='principal.contrataciones')),
                ('id_tipo_despido', models.ForeignKey(db_column='id_tipo_despido', on_delete=django.db.models.deletion.CASCADE, to='principal.tipodespido')),
            ],
            options={
                'db_table': 'contrato_fin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposDeContrato',
            fields=[
                ('id_tipo_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_contrato', models.CharField(max_length=100)),
                ('asigna_rol', models.BooleanField()),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.roles')),
            ],
            options={
                'db_table': 'tipos_de_contrato',
                'ordering': ['nombre_tipo_contrato'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contrataciones',
            name='id_tipo_contrato',
            field=models.ForeignKey(blank=True, db_column='id_tipo_contrato', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.tiposdecontrato'),
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aforo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('id_area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.CASCADE, to='principal.areas')),
                ('id_piso', models.ForeignKey(db_column='id_piso', on_delete=django.db.models.deletion.CASCADE, to='principal.pisos')),
            ],
            options={
                'db_table': 'ubicaciones',
                'ordering': ['nombre_ubicacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('foto_perfil', models.ImageField(blank=True, default='usuario.png', null=True, upload_to='foto_usuarios/')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_residencia', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='pre_registro', max_length=50)),
                ('id_departamento_expedicion', models.ForeignKey(db_column='id_departamento_expedicion', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_expedicion', to='principal.departamentos')),
                ('id_departamento_expulsor', models.ForeignKey(blank=True, db_column='id_departamento_expulsor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_expulsor', to='principal.departamentos')),
                ('id_departamento_nacimiento', models.ForeignKey(db_column='id_departamento_nacimiento', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_nacimiento', to='principal.departamentos')),
                ('id_departamento_residencia', models.ForeignKey(db_column='id_departamento_residencia', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_residencia', to='principal.departamentos')),
                ('id_eps', models.ForeignKey(db_column='id_eps', on_delete=django.db.models.deletion.CASCADE, to='principal.eps')),
                ('id_estado_civil', models.ForeignKey(db_column='id_estado_civil', on_delete=django.db.models.deletion.CASCADE, to='principal.estadocivil')),
                ('id_estrato', models.ForeignKey(db_column='id_estrato', on_delete=django.db.models.deletion.CASCADE, to='principal.estratosocioeconomico')),
                ('id_etnia', models.ForeignKey(db_column='id_etnia', on_delete=django.db.models.deletion.CASCADE, to='principal.etnia')),
                ('id_municipio_expedicion', models.ForeignKey(db_column='id_municipio_expedicion', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_expedicion', to='principal.municipios')),
                ('id_municipio_expulsor', models.ForeignKey(blank=True, db_column='id_municipio_expulsor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_expulsor', to='principal.municipios')),
                ('id_municipio_nacimiento', models.ForeignKey(db_column='id_municipio_nacimiento', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_nacimiento', to='principal.municipios')),
                ('id_municipio_residencia', models.ForeignKey(db_column='id_municipio_residencia', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_residencia', to='principal.municipios')),
                ('id_pais', models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.paises')),
                ('id_sede', models.ForeignKey(db_column='id_sede', on_delete=django.db.models.deletion.CASCADE, to='principal.sedes')),
                ('id_sexo', models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.CASCADE, to='principal.sexo')),
                ('id_sisben', models.ForeignKey(db_column='id_sisben', on_delete=django.db.models.deletion.CASCADE, to='principal.sisben')),
                ('id_tipo_discapacidad', models.ForeignKey(db_column='id_tipo_discapacidad', on_delete=django.db.models.deletion.CASCADE, to='principal.tipodiscapacidad')),
                ('id_tipo_identificacion', models.ForeignKey(db_column='id_tipo_identificacion', on_delete=django.db.models.deletion.CASCADE, to='principal.tipoidentificacion')),
                ('id_tipo_sangre', models.ForeignKey(db_column='id_tipo_sangre', on_delete=django.db.models.deletion.CASCADE, to='principal.tiposangre')),
                ('id_zona_residencial', models.ForeignKey(db_column='id_zona_residencial', on_delete=django.db.models.deletion.CASCADE, to='principal.zonaresidencial')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['nombres'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pagos',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios'),
        ),
        migrations.AddField(
            model_name='matriculasfinancieras',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios'),
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id_credencial', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios')),
            ],
            options={
                'db_table': 'credenciales',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contrataciones',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios'),
        ),
        migrations.AddField(
            model_name='cartera',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios'),
        ),
        migrations.CreateModel(
            name='UsuarioRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='principal.roles')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios')),
            ],
            options={
                'db_table': 'usuario_roles',
                'managed': True,
                'unique_together': {('id_usuario', 'id_rol')},
            },
        ),
    ]
