# Generated by Django 5.1.2 on 2025-04-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paises',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.paises'),
        ),
    ]
