# Generated by Django 5.1.2 on 2025-04-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorEstudiantes',
            fields=[
                ('anio_ingreso', models.IntegerField(primary_key=True, serialize=False)),
                ('ultimo_consecutivo', models.IntegerField()),
            ],
            options={
                'db_table': 'contador_estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ocupaciones',
            fields=[
                ('id_ocupacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ocupacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocupaciones',
                'ordering': ['id_ocupacion'],
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Semestres',
            new_name='SemestresPensum',
        ),
        migrations.AlterModelOptions(
            name='modulos',
            options={'managed': True, 'ordering': ['id_modulo']},
        ),
        migrations.AlterModelOptions(
            name='tiposprogramas',
            options={'managed': True, 'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='pensum',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programasacademicos',
            name='acto_administrativo_pdf',
            field=models.ImageField(blank=True, null=True, upload_to='anexos/gestion_academica/'),
        ),
        migrations.AddField(
            model_name='programasacademicos',
            name='codigo_siet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programasacademicos',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programasacademicos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programasacademicos',
            name='numero_certificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programasacademicos',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_estudiante', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('semestre_actual', models.IntegerField()),
                ('estado_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='principal.programasacademicos')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios')),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentosEstudiantes',
            fields=[
                ('id_documento_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('ruta_archivo', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='principal.estudiantes')),
            ],
            options={
                'db_table': 'documentos_estudiantes',
                'managed': True,
            },
        ),
    ]
