# Generated by Django 5.1.2 on 2025-04-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_contadorestudiantes_ocupaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pensum',
            options={'managed': True, 'ordering': ['anio_vigencia']},
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_sede',
        ),
    ]
