# Generated by Django 5.1.2 on 2025-04-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_pensum_options_remove_usuarios_id_sede'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semestrespensum',
            table='semestres_pensum',
        ),
    ]
