# Generated by Django 5.1.2 on 2025-05-03 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_semestrespensum_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'permisos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermisos',
            fields=[
                ('id_usuario_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, db_column='asignado_por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariopermisos_asignado_por_set', to='principal.usuarios')),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='principal.permisos')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios')),
            ],
            options={
                'db_table': 'usuario_permisos',
                'managed': True,
                'unique_together': {('id_usuario', 'id_permiso')},
            },
        ),
    ]
