# Generated by Django 5.1.2 on 2025-05-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_adjuntomensaje_conversacion_grupochat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjuntomensaje',
            options={'managed': True, 'verbose_name': 'Adjunto', 'verbose_name_plural': 'Adjuntos'},
        ),
        migrations.AlterModelOptions(
            name='conversacion',
            options={'managed': True, 'ordering': ['-ultima_actividad'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='grupochat',
            options={'managed': True, 'verbose_name': 'Grupo de chat', 'verbose_name_plural': 'Grupos de chat'},
        ),
        migrations.AlterModelOptions(
            name='grupoconversacion',
            options={'managed': True, 'verbose_name': 'Relación Grupo-Conversación', 'verbose_name_plural': 'Relaciones Grupo-Conversación'},
        ),
        migrations.AlterModelOptions(
            name='lecturamensaje',
            options={'managed': True, 'verbose_name': 'Lectura', 'verbose_name_plural': 'Lecturas'},
        ),
        migrations.AlterModelOptions(
            name='mencionmensaje',
            options={'managed': True, 'verbose_name': 'Mención', 'verbose_name_plural': 'Menciones'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'managed': True, 'ordering': ['fecha_envio'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='mensajefavorito',
            options={'managed': True, 'verbose_name': 'Mensaje favorito', 'verbose_name_plural': 'Mensajes favoritos'},
        ),
        migrations.AlterModelOptions(
            name='notificacionchat',
            options={'managed': True, 'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='participanteconversacion',
            options={'managed': True, 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='reaccionmensaje',
            options={'managed': True, 'verbose_name': 'Reacción', 'verbose_name_plural': 'Reacciones'},
        ),
    ]
