# Generated by Django 5.1.2 on 2025-05-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_adjuntomensaje_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id_anio', models.AutoField(primary_key=True, serialize=False)),
                ('anio_academico', models.IntegerField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anio',
                'ordering': ['id_anio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_modificada', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('sentencia_sql', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsecutivosTipoPago',
            fields=[
                ('tipo_pago', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ultimo_numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consecutivos_tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosInscripcion',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estados_inscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscripcionesEstudiantes',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('semestre', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inscripciones_estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemestresProgramas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'semestres_programas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIngresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_ingreso_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMatriculaFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_matricula_fin',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='adjuntomensaje',
            options={'managed': False, 'verbose_name': 'Adjunto', 'verbose_name_plural': 'Adjuntos'},
        ),
        migrations.AlterModelOptions(
            name='administradoraspensiones',
            options={'managed': False, 'ordering': ['nombre_administradora']},
        ),
        migrations.AlterModelOptions(
            name='areas',
            options={'managed': False, 'ordering': ['id_area']},
        ),
        migrations.AlterModelOptions(
            name='arl',
            options={'managed': False, 'ordering': ['nombre_arl']},
        ),
        migrations.AlterModelOptions(
            name='bancos',
            options={'managed': False, 'ordering': ['nombre_banco']},
        ),
        migrations.AlterModelOptions(
            name='cajascompensacion',
            options={'managed': False, 'ordering': ['nombre_caja']},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='cartera',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conceptospago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conciliaciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contadorestudiantes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contrataciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contratofin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='convenios',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conversacion',
            options={'managed': False, 'ordering': ['-ultima_actividad'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='costosprogramas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='credenciales',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cuotas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='departamentolaboral',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'managed': False, 'ordering': ['departamento']},
        ),
        migrations.AlterModelOptions(
            name='descuentos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='documentoscontrato',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='documentosestudiantes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eps',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='escuelas',
            options={'managed': False, 'ordering': ['id_escuelas']},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='estratosocioeconomico',
            options={'managed': False, 'ordering': ['estrato']},
        ),
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='etnia',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='financiaciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='formapago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grupochat',
            options={'managed': False, 'verbose_name': 'Grupo de chat', 'verbose_name_plural': 'Grupos de chat'},
        ),
        migrations.AlterModelOptions(
            name='grupoconversacion',
            options={'managed': False, 'verbose_name': 'Relación Grupo-Conversación', 'verbose_name_plural': 'Relaciones Grupo-Conversación'},
        ),
        migrations.AlterModelOptions(
            name='incrementos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jornadas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecturamensaje',
            options={'managed': False, 'verbose_name': 'Lectura', 'verbose_name_plural': 'Lecturas'},
        ),
        migrations.AlterModelOptions(
            name='matriculasfinancieras',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mediospago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mencionmensaje',
            options={'managed': False, 'verbose_name': 'Mención', 'verbose_name_plural': 'Menciones'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'managed': False, 'ordering': ['fecha_envio'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='mensajefavorito',
            options={'managed': False, 'verbose_name': 'Mensaje favorito', 'verbose_name_plural': 'Mensajes favoritos'},
        ),
        migrations.AlterModelOptions(
            name='modulos',
            options={'managed': False, 'ordering': ['id_modulo']},
        ),
        migrations.AlterModelOptions(
            name='moduloscompetencias',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'managed': False, 'ordering': ['municipio']},
        ),
        migrations.AlterModelOptions(
            name='notificacionchat',
            options={'managed': False, 'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='ocupaciones',
            options={'managed': False, 'ordering': ['id_ocupacion']},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pagoscuotas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='participanteconversacion',
            options={'managed': False, 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='pensum',
            options={'managed': False, 'ordering': ['anio_vigencia']},
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pisos',
            options={'managed': False, 'ordering': ['id_piso']},
        ),
        migrations.AlterModelOptions(
            name='programasacademicos',
            options={'managed': False, 'ordering': ['id_programa']},
        ),
        migrations.AlterModelOptions(
            name='reaccionmensaje',
            options={'managed': False, 'verbose_name': 'Reacción', 'verbose_name_plural': 'Reacciones'},
        ),
        migrations.AlterModelOptions(
            name='riesgolaboral',
            options={'managed': False, 'ordering': ['nivel_riesgo']},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sedes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='semestrespensum',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'managed': False, 'ordering': ['sexo']},
        ),
        migrations.AlterModelOptions(
            name='sisben',
            options={'managed': False, 'ordering': ['sisben']},
        ),
        migrations.AlterModelOptions(
            name='tipodespido',
            options={'managed': False, 'ordering': ['nombre_despido']},
        ),
        migrations.AlterModelOptions(
            name='tipodiscapacidad',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipoidentificacion',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tiposangre',
            options={'managed': False, 'ordering': ['id_tipo_sangre']},
        ),
        migrations.AlterModelOptions(
            name='tiposdecontrato',
            options={'managed': False, 'ordering': ['nombre_tipo_contrato']},
        ),
        migrations.AlterModelOptions(
            name='tiposmodulo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tiposprogramas',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={'managed': False, 'ordering': ['nombre_ubicacion']},
        ),
        migrations.AlterModelOptions(
            name='usuariopermisos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarioroles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False, 'ordering': ['nombres']},
        ),
        migrations.AlterModelOptions(
            name='zonaresidencial',
            options={'managed': False, 'ordering': ['zona_residencial']},
        ),
        migrations.DeleteModel(
            name='Anios',
        ),
    ]
